### ISSUE TITLE
Исправить обращение к сервису

### ISSUE THREAD

**Issue by micolla** [micolla/WebStoreASP#20]
Почемуто не вызывается API через приложение, но если поработать PostMan, то вызывается через строку
http://localhost:61311/api/orders/ddd

_Originally posted by @micolla in https://github.com/micolla/WebStoreASP/pull/18_

**Comment by Infarh** [comment]
Решение проблемы https://github.com/micolla/WebStoreASP/pull/18/commits/f70874b35f3b1a717da4c15ac37131b6eafd1c2e#r375797896
